# Generated by Django 4.2.dev20220827135108 on 2022-09-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
            },
        ),
        migrations.AlterModelOptions(
            name="poll",
            options={"verbose_name": "Опрос", "verbose_name_plural": "Опросы"},
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="poll",
            new_name="poll_id",
        ),
        migrations.AlterField(
            model_name="comment",
            name="comment_text",
            field=models.CharField(max_length=255, verbose_name="Текст комментария"),
        ),
    ]
