# Generated by Django 4.2.dev20220827135108 on 2022-09-22 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_alter_comment_options_alter_poll_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="poll_id",
            new_name="poll",
        ),
    ]
