# Generated by Django 4.2.dev20220827135108 on 2022-10-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0006_alter_timetable_weekday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="name",
            field=models.CharField(max_length=130, verbose_name="Название дисциплины"),
        ),
    ]
