# Generated by Django 4.2.dev20220827135108 on 2022-10-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0007_alter_subject_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timetable",
            name="room",
            field=models.CharField(max_length=10, verbose_name="Аудитория"),
        ),
        migrations.AlterField(
            model_name="timetable",
            name="time",
            field=models.CharField(max_length=40, verbose_name="Время"),
        ),
        migrations.AlterField(
            model_name="timetable",
            name="weekday",
            field=models.CharField(max_length=30, verbose_name="День"),
        ),
    ]
